### ISSUE TITLE
ImportError: cannot import 'json_available' from 'flask'

### ISSUE THREAD

**Issue by leblancfg** [cookiecutter-flask/cookiecutter-flask#517] opened 2019-07-11 19:32 UTC
Tried installing the template, and I get an ImportError when following the steps in `README.rst`:

~~~python
ImportError: cannot import 'json_available' from 'flask'
~~~

## Research
Taking a look at the [Flask changelog](https://flask.palletsprojects.com/en/1.1.x/changelog/?highlight=json_available), we see:

>### Version 1.1.1
>
>*Released 2019-07-08*
>
>    The flask.json_available flag was added back for compatibility with some extensions. It will raise a deprecation warning when used, and will be removed in version 2.0.0. [#3288](https://github.com/pallets/flask/issues/3288)

### Quick fix
Bumping the flask version in `Pipfile` to 1.1.1. Users will get a deprecation warning, and the issue will need to be solved when flask 2.0.0 gets released. There is already a pull request for this (#515), which somehow is [failing in CI](https://travis-ci.org/cookiecutter-flask/cookiecutter-flask/jobs/556151424) for an unrelated reason.

### Real fix
I don't know enough about Flask to understand how the `json_available` flag is being used to suggest a better course of action, but it need to be done in the "medium" future.

**Comment by jamescurtin** [comment] 2019-07-12 02:12
Thanks for raising this! I've just merged #515 to address this immediate issue. The erroneously failing CI is caused by [poorly pinned dependencies](https://gitlab.com/pycqa/flake8-docstrings/issues/36) in a Flake8 plugin dependency (FYI in case you need to update the pinned version of `flake8-docstrings` in any projects you've already created once the fix is released).

We only use `json_available` in this project indirectly (_e.g._ the flask debug toolbar). I'd expect that this will be fixed in those libraries soon--but if not, we can always make a PR! 😄

**Closed by jamescurtin** 2019-07-12 02:12 UTC

**Comment by jeffwidman** [comment] 2020-02-22 06:02
@jamescurtin maintainer of Flask-DebugToolbar here, FYI that I just pushed a release that removes the `json_available` dependency, so you can now use `Flask-DebugToolbar` `0.11` with any reasonably modern version of Flask.
